### ISSUE TITLE
IndexError: index 409600 is out of bounds for axis 0 with size 409600

### ISSUE THREAD

**Issue by gaoxumustwin** [cqu20160901/yolov8n_onnx_tensorRT_rknn_horizon_dfl#5]
作者您好，我未修改代码中的任何地方，直接运行出现
predbox = postprocess(out, img_h, img_w) in postprocess
    cls_val = cls[cl * mapSize[index][0] * mapSize[index][1] + h * mapSize[index][1] + w]
IndexError: index 409600 is out of bounds for axis 0 with size 409600

**Comment by cqu20160901** [comment]
模型是我仓库中提供的吗？

**Comment by gaoxumustwin** [comment]
![12](https://github.com/cqu20160901/yolov8n_onnx_tensorRT_rknn_horizon_dfl/assets/76648474/6a05b818-d632-41b1-a0af-8b31f90dc952)
对的 佬 直接使用的您仓库中的东西

**Comment by gaoxumustwin** [comment]
佬 我的 rknn-toolkit2 版本为最新版的 2.0.0b0+9bab5682

**Comment by cqu20160901** [comment]
把这两行
reg = output[index * 2 + 0]
 cls = output[index * 2 + 1]
改成以下两行
reg = output[index * 2 + 1]
cls = output[index * 2 + 0]

**Comment by gaoxumustwin** [comment]
厉害了 佬 请问已成功运行！！

**Comment by KaaiLee** [comment]
对了，大佬，按照你说的改完转rknn的代码后，c++版的推理代码是不是后处理也要改一下，我没修改c++代码，用上面更新的py转rknn模型后，c++推理出来很多蓝色框框
